name: Build Check

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2-beta
              with:
                  fetch-depth: 1
            - name: Installing packages
              run: |
                  npm install
                  npm --prefix ./packages/goober-autoprefixer install ./packages/goober-autoprefixer
            - name: Run tests
              run: npm run test
