name: Build Check

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2-beta
              with:
                  fetch-depth: 1
            - name: Installing packages
              run: |
                  npm install
                  cd packages/goober-prefixer
                  npm install
                  cd ../..
            - name: Run tests
              run: npm run test
