name: Build Check

on: [pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
          matrix:
            # Change the condition for ESM Dist Test below when changing this.
            node-version: [10.x, 12.x, 14.x]

        steps:
            - uses: actions/checkout@v2-beta
              with:
                  fetch-depth: 1
            - name: Installing packages
              run: npm install
            - name: Run tests
              run: npm run test
            - if: matrix.node-version == '14.x'
              name: ESM Dist Test
              run: npm run test:dist
